/atom/movable/proc/thrown_at(var/atom/target, var/mob/thrower)
	force_move(get_turf(src))
	play_local_sound(src, 'sounds/effects/whoosh1.wav', 100)
	var/vector/V = new(src, thrower, target)
	V.Initialize()
