language: generic
sudo: false

env:
  global:
    BYOND_MAJOR="511"
    BYOND_MINOR="1381"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

script:
  - (! grep 'step_[xy]' maps/*.dmm) 
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - sed -i '1s/^/#define TRAVIS_TEST\n\n/' code/world.dm
  - DreamMaker antimonium.dme > log.txt
  - (grep "0 errors, 0 warnings" log.txt)
  - DreamDaemon antimonium.dmb -invisible -trusted -core 2>&1 | tee log.txt
  - (! grep "runtime error:" log.txt)
  - (! grep "WARNING:" log.txt)
  - (! grep "ERROR:" log.txt)
