/mob/animal/CreateUI()
	inventory_slots[SLOT_MOUTH] = new /obj/ui/inv/hand(src, "mouth", "3,1", SLOT_MOUTH, _associated_limb = BP_HEAD)
	inventory_slots[SLOT_OVER] =  new /obj/ui/inv/gear(src, "body",  "1,2", SLOT_OVER,  SLOT_FLAG_OVER)
	inventory_slots[SLOT_BACK] =  new /obj/ui/inv/gear(src, "back",  "1,3", SLOT_BACK,  SLOT_FLAG_BACK)
	inventory_slots[SLOT_HAT] =   new /obj/ui/inv/gear(src, "head",  "1,4", SLOT_HAT,   SLOT_FLAG_HAT)
	..()
