#define PERMISSIONS_DEBUG     1
#define PERMISSIONS_MODERATOR 2
#define PERMISSIONS_FUN       4
#define PERMISSIONS_SECURE    8
#define PERMISSIONS_DEFAULT (PERMISSIONS_DEBUG|PERMISSIONS_MODERATOR|PERMISSIONS_FUN|PERMISSIONS_SECURE)
